## https://issuecloser.com/blog/deploying-sinatra-app-to-heroku
development:
  adapter: postgresql
  database: database.db
test:
    adapter: postgresql
    database: database.db
production:
  adapter: postgresql
  database: database.db


# # THE ORIGINAL
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3


# development:
#   adapter: sqlite3
#   database: database.db

# test:
#   adapter: sqlite3
#   database: database.db

# production:
#   adapter: postgresql
#   # database: sch_database #rename this to whatever you want
#   database: mydb
#   username: username
#   password: password
#   host: localhost

# ## config'd via http://lucaskisabeth.com/2017/06/24/deploying_your_sqlite3_sinatra_app_to_heroku_using_postgresql/