## THE ORIGINAL
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

# default: &default
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   adapter: sqlite3
#   database: db/development.sqlite3

# test:
#   <<: *default
#   adapter: sqlite3
#   database: db/test.sqlite3

# production:
#   <<: *default
#   adapter: postgresql
#   database: 


# FROM THE MEDIUM PAGE OF A FORMER STUDENT
# ## FROM https://medium.com/@isphinxs/deploying-a-sinatra-app-to-heroku-7944b024f77c
development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.db
  host: localhost
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: <%= ENV["DATABASE_HOST"] %>
  pool: 5