default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
 database: music_backend

test:
  <<: *default
database: music_backend

production:
  <<: *default
  database: music_backend
